"""Verify that the re-fit re-implementations, run with AS-PUBLISHED coefficients,
reproduce the paper's precomputed R34 (generated by wind_profiles.py in script 02).
If mine == precomputed per snapshot, the equations are correct."""
import numpy as np, pandas as pd, sys
sys.path.insert(0, 'TCRR20260037_revision_bundle')
import wind_profiles as wp
BUN='TCRR20260037_revision_bundle'; R=np.arange(0,500.001,1.0)
df=pd.read_csv(f'{BUN}/metrics_by_snapshot.csv')
cat=pd.read_csv(f'{BUN}/snapshot_catalog.csv')[['SID','ISO_TIME','BASIN']]
df=df.merge(cat,on=['SID','ISO_TIME'],how='left'); df=df[df.BASIN=='WP'].copy()
d=df[(df.VMAX>=34)&(df.RMAX>0)&df.LAT.notna()&df.OBS_R34.notna()].copy()
V,Rm,La,Pc=d.VMAX.values,d.RMAX.values,np.abs(d.LAT.values),d.PC.values

def last_cross(vkt,valid):
    ge=vkt>=34.0;anyc=ge.any(axis=1);last=ge.shape[1]-1-np.argmax(ge[:,::-1],axis=1)
    return np.where(valid&anyc,R[last],np.nan)
# --- my re-implementations at AS-PUBLISHED params ---
rank_mine=Rm*(V/34.0)**2.0                                      # alpha=0.5
def h80(kB=1.,penv=1013.):
    dp=(penv-Pc)*100.;f=2*wp.OMEGA*np.sin(np.radians(La));vms=V*wp.KT_TO_MS
    with np.errstate(all='ignore'):B=np.clip((vms**2*wp.RHO*wp.E_EULER)/np.where(dp>0,dp,np.nan)*kB,1.,2.5)
    rm=Rm*wp.NM_TO_M;rmm=np.maximum(R[None,:]*wp.NM_TO_M,1.);rr=(rm[:,None]/rmm)**B[:,None]
    vp=np.sqrt((B[:,None]/wp.RHO)*rr*dp[:,None]*np.exp(-rr)+(rmm*f[:,None]/2)**2)-rmm*f[:,None]/2
    return last_cross(np.maximum(vp,0)*wp.MS_TO_KT,(dp>0))
def h10(kbs=1.,penv=1013.):
    dp=penv-Pc;bs=np.clip((-4.4e-5*dp**2+0.01*dp-0.014*La+1.0)*kbs,0.5,2.5)
    rr=Rm[:,None]/np.maximum(R[None,:],0.01);vf=(rr**bs[:,None]*np.exp(1-rr**bs[:,None]))**0.5
    return last_cross(V[:,None]*vf,(dp>0))
def willR(v,rm,la,s=1.,thr=34.):
    vms=v*wp.KT_TO_MS
    n=np.clip(0.4067+0.0144*vms-0.0038*la,.2,2.4);X1=max(317.1-2.026*vms+1.915*la,50.)*s;X2=25.
    A=np.clip(0.0696+0.0049*vms-0.0064*la,0,1);rmk=rm*wp.NM_TO_M/1000;rk=R*wp.NM_TO_M/1000
    Xe=(1-A)*X1+A*X2;R1=wp._find_R1(rmk,Xe,n,25.);R2=R1+25
    vin=v*(np.maximum(rk,1e-6)/rmk)**n;dr=rk-rmk;vo=v*((1-A)*np.exp(-dr/X1)+A*np.exp(-dr/X2))
    xi=np.clip((rk-R1)/25.,0,1);w=wp._bellramp(xi);vt=vin*(1-w)+vo*w
    vv=np.where(rk<=R1,vin,np.where(rk<=R2,vt,vo));vv[R==0]=0;a=vv>=thr
    return float(R[np.where(a)[0][-1]]) if a.any() else np.nan
will_mine=np.array([willR(v,rm,la) for v,rm,la in zip(V,Rm,d.LAT.values)])
def cle_mine_one(v,rm,la):
    try:prof=wp.chavas2015(R,v,rm,la)   # internal (as-published) Ck/Cd
    except Exception:return np.nan
    ge=prof>=34.
    return float(R[np.where(ge)[0][-1]]) if np.isfinite(prof).any() and ge.any() else np.nan

pairs=[('Rankine',rank_mine),('Holland1980',h80(1.)),('Holland2010',h10(1.)),('Willoughby2006',will_mine)]
print(f"{'Model':16s} {'N':>6s} {'mean|d|':>8s} {'max|d|':>7s} {'# > 1nm':>8s}   (mine vs paper precomputed R34)")
for name,mine in pairs:
    pc=d[f'{name}_R34'].values;m=np.isfinite(mine)&np.isfinite(pc);dd=np.abs(mine[m]-pc[m])
    print(f"{name:16s} {m.sum():6d} {dd.mean():8.3f} {dd.max():7.2f} {int((dd>1).sum()):8d}")
# CLE15 on a 500 subsample (slow)
np.random.seed(1); s=np.random.choice(len(d),500,replace=False)
cm=np.array([cle_mine_one(V[i],Rm[i],d.LAT.values[i]) for i in s]);pc=d['Chavas2015_R34'].values[s]
m=np.isfinite(cm)&np.isfinite(pc);dd=np.abs(cm[m]-pc[m])
print(f"{'Chavas2015':16s} {m.sum():6d} {dd.mean():8.3f} {dd.max():7.2f} {int((dd>1).sum()):8d}  (500-snapshot subsample; uses wp.chavas2015 directly)")
